services:
  - type: web
    name: Env
    env: python
    plan: free          # ou free si tu veux tester
    buildCommand: |
      pip install -r requirements.txt
      chmod +x piper/piper
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: PYTHON_VERSION
        value: 3.11.0
